version: "3"
services:
    phone_api:
      build: ./server
      image: 'phone_api'
      environment:
        NODE_ENV: production
        DATABASE_NAME: 'phone_prod'
        DATABASE_USER: 'postgres'
        DATABASE_PASSWORD: 'postgres'
        DATABASE_HOST: 'phone_db'
        DATABASE_PORT: '5432'
      depends_on:
        - phone_db
      links:
        - phone_db

    phone_db:
      container_name: 'phone_db'
      image: postgres
      environment:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_DB: 'phone_prod'
      ports:
        - 5432:5432

    phone_client:
      container_name: phone_client
      build:
        context: ./react-app
        dockerfile: Dockerfile
      environment:
        NODE_ENV: production 

    phone_gateway:
      container_name: phone_gateway
      image: nginx
      depends_on:
        - phone_api
        - phone_client
      links:
        - phone_api
        - phone_client
      ports:
        - 8080:80
      volumes:
        - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf